### ISSUE TITLE
[Proposal] Add "Genres/Categories"

### ISSUE THREAD

**Issue by AndrewKeepCoding** [matthiasjost/dotnet-content-creators#37]
It'd be easier to browse the list if you could see what **Genre** or **Category** each content creator specializes.

For example:
    - General .NET
    - Windows Desktop
    - Azure
    - ASP.NET
    - etc...

**Comment by matthiasjost** [comment]
Sounds like a good idea! I wil think about it. I am currently also working on a web version built with Vue.js that could offer more comfortable browsing.

**Comment by dracan** [comment]
> I am currently also working on a web version built with Vue.js that could offer more comfortable browsing.

Surely that should be Blazor! 😂

**Comment by matthiasjost** [comment]
The backend is in ASPNET Core 😋

**Comment by matthiasjost** [comment]
@AndrewKeepCoding So essentially a new column in the table listing genres/categories (tags?)? 

Either just a comma-separated list or something fancier that looks like a "Chip" (https://vuetifyjs.com/en/components/chips/)?

I wonder if that should be done in this markdown file or if I just implement it in the web app version.

**Comment by AndrewKeepCoding** [comment]
@matthiasjost Sorry, I don't have much experience with web apps. "Chip" looks good though. But at least, it's easy to add a column for **Tags** in the markdown and let collaborators fill them.

**Comment by matthiasjost** [comment]
Sounds like a good plan! We could add a Tag column and start to fill it.

**Comment by AndrewKeepCoding** [comment]
You sound busy with your web app. Can I create a PR?

**Comment by matthiasjost** [comment]
Highly appreciated!

**Comment by AndrewKeepCoding** [comment]
Done.

**Comment by matthiasjost** [comment]
Merged. Thank you!

**Comment by AndrewKeepCoding** [comment]
#38 closes this.
