### ISSUE TITLE
Adding to the list

### ISSUE THREAD

**Issue by JesseLiberty** [matthiasjost/dotnet-content-creators#46]
Sorry to be stupid but I can't figure out how to add myself to the list.

Jesse Liberty
https://jesseliberty.com
.NET MAUI, C#

**Comment by matthiasjost** [comment]
Thanks for your issue, Jesse!

You may open a PR, or I can add you.

- What is the country you want to be added to?

- Are there any other channels like Twitter or LinkedIn you want to have added?

**Comment by matthiasjost** [comment]
@JesseLiberty You have been added to the list!
