### ISSUE TITLE
Split Creators based on Language instead of Country

### ISSUE THREAD

**Issue by shoaibshakeel381** [matthiasjost/dotnet-content-creators#55]
I doubt categorizing based on country has any benefit. Instead categorization based on language, content type or content platform would be more useful.

**Comment by matthiasjost** [comment]
Thanks for your issue Shoaib. Currently we only have English content. the initial idea was to have some criteria to divide the list and to motivate people nominate others from their country.

But it would be cool to have an alternative view on the list where you can sort by tags.

I started with a separate web project but it hasn't been finished so far. It collects all creators from this list and offers a different view.
